### ISSUE TITLE
min- / maxItems for dicts

### ISSUE THREAD

**Issue by Heiko-san** [jamesturk/validictory#101]
I could have used that feature a several times lately.
If you have the case that at a layer you can't say how the keys will be named and have to work with additionalProperties and/or patternProperties your schema will also pass if there is not a single property present at the data.
Or if you have properties that all have required=False because they are interchangeable.

However this is not always the intended behavior in most cases you would like to express "there must be at least 1".

The only intuitive solution I found in the docs is to add minItems and/or maxItems, which right now seem to only work for arrays and be ignored in a type object layer.

**Comment by jamesturk** [comment]
Hi, I'd be open to a making this work if you would be able to find some time to come up with some test cases for the expected behavior.

**Comment by bmdemouser** [comment]
A real world example can be found in the code from #100:
```
                    'modules': {
                        'additionalProperties': False,
                        'type': 'object',
                        'properties': {
                            'statuscode': {

```

**Comment by Heiko-san** [comment]
Sorry for posting with the wrong account, it was me ... ^^'

**Comment by Heiko-san** [comment]
Truns out (after having a deeper look into your code) this is done really easily, I was just experimenting:
```
hfi@hfi-UX305LA ~/git/validictory $ ./test.py 
--------------------------
should_also_pass passed
should_also_pass_multi_value passed
should_fail_too_few failed with: Value {} for field '<obj>' must have number of properties greater than or equal to 1
should_fail_too_many failed with: Value {'three': 3, 'two': 2, 'one': 1} for field '<obj>' must have number of properties less than or equal to 2
should_fail_unknown_item failed with: Value {'four': 4} for field '<obj>' contains additional property 'four' not defined by 'properties' or 'patternProperties' and additionalProperties  is False
should_pass passed
--------------------------
should_also_pass passed
should_also_pass_multi_value passed
should_fail_too_few failed with: Value {} for field '<obj>' must have number of properties greater than or equal to 1
should_fail_too_many failed with: Value {'three': 3, 'two': 2, 'one': 1} for field '<obj>' must have number of properties less than or equal to 2
should_fail_unknown_item failed with: Value {'four': 4} for field '<obj>' contains additional property 'four' not defined by 'properties' or 'patternProperties' and additionalProperties  is False
should_pass passed
```
I will try to write some test for it and issue another pull request :)

PS I'm using "minProperties" and "maxProperties"  now

**Comment by jamesturk** [comment]
wanted to confirm that min/max properties fixes this one, OK to close?
