### ISSUE TITLE
List of types raises SchemaError on unknown property

### ISSUE THREAD

**Issue by sebjamesfd** [jamesturk/validictory#107]
Thanks for the great work on validictory!

I think I've come across a bug when trying to use a list of types against a property in a schema. 

If the validator has set 'disallow_unknown_properties=True' then if it catches an unknown property it will raise a SchemaError but because 'validate_type' only catches ValidationError (https://github.com/jamesturk/validictory/blob/master/validictory/validator.py#L249) then it will error before it is able to move on to the next type declaration in the list provided by the schema.

I've reproduced in a test here https://github.com/sebjamesfd/validictory/blob/type-list-schemerror/validictory/tests/test_disallow_unknown_properties.py#L52

Could add SchemaError to the except within 'validate_type' to catch it in this case?

**Comment by jamesturk** [comment]
thanks for the report! would you mind adding your test as a PR?

**Comment by sebjamesfd** [comment]
@jamesturk Thanks for merging the PR! What sort of time frame are you thinking for the next release?

**Comment by jamesturk** [comment]
working on a release of 1.1 now
