### ISSUE TITLE
handling $ref pointers to other schemas?

### ISSUE THREAD

**Issue by ghost** [jamesturk/validictory#20]
Hi James and Sunlight Labs,

Is there support for $ref pointers in validictory?  This is defined in draft-03 of the json-schema spec.  It allows a schema to define types by referring to a schema at a URL.

Here is an example of such a schema:

http://trec-kba.org/schemas/v1.0/stream-item.json

which has a $ref to other schemas, like this one:

http://trec-kba.org/schemas/v1.0/content-item.json

jrf

**Comment by iandanforth** [comment]
For anyone else who get's here you may want to look at https://github.com/Julian/jsonschema as a replacement for validictory that supports up to draft04

**Comment by vitaly-krugl** [comment]
Thanks for mentioning it @iandanforth!

**Comment by dmr** [comment]
I use validictory in production with $ref without problems and it's working really good. Are you missing any other draft4 features besides $ref @iandanforth?

**Comment by iandanforth** [comment]
@dmr Just that, and your solution almost works for my use-case. I also need to reference other files, not just internal refs. the RefResolver in jsonschema handles this, but I'd much prefer a pre-processor like yours.

**Comment by iandanforth** [comment]
@dmr nevermind I just figured out how to use https://github.com/gazpachoking/jsonref to do this.

import jsonref
import validictory

    # Load that schema containing $refs
    with open(<path_to_schema_file>) as fh:
        base_uri = "file://" + <path_to_base_schema_file> + "/"
        schema = jsonref.load(fh, base_uri)

    # Validate the data against the schema
    if not validictory.validate(data, schema):
        print("Data is valid")
