### ISSUE TITLE
JSON-Schema Test Suite

### ISSUE THREAD

**Issue by dmr** [jamesturk/validictory#75]
I quickly ran the "JSON-Schema-Test-Suite" that apparently many projects are using:
https://github.com/json-schema/JSON-Schema-Test-Suite:

```
Ran 245 tests in 0.147 seconds
FAILED (failures=37, errors=107, skipped=0)
```

I can share the results and commit my code if anybody is interested. Most cases fail for good reasons I think.

What are your opinions about a test suite like this?

I think it would be good to know which features from the specification are supported and which are not.

**Comment by jamesturk** [comment]
closed in light of #114
