### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by lwm** [jamesturk/validictory#91]
A `validictory.validate(a,b)` can, for example, raise a `FieldValidationError`. I would like to have access to the `value`, the `constraint` (maxLength, minLength) and the `field` so I can customise my error messages.

So far, we have:
```
ipdb> err
FieldValidationError("Value u'aaaaaaaaaaaaaaa' for field '<obj>[0]' must have length greater than or equal to 16",)
ipdb> err.
err.args       err.fieldname  err.message    err.value      
ipdb> err.args
("Value u'aaaaaaaaaaaaaaa' for field '<obj>[0]' must have length greater than or equal to 16",)
ipdb> err.fieldname
'[list item]'
ipdb> err.message
"Value u'aaaaaaaaaaaaaaa' for field '<obj>[0]' must have length greater than or equal to 16"
ipdb> err.value
u'aaaaaaaaaaaaaaa'
```

I can't programmatically do much with `[list item]` when it really should have been `id` (the key of the property being validated) and I can't tell that it was actually a `minLength` error.

Can anything be done here?

**Comment by jamesturk** [comment]
the fact that fieldname is [list item] when it is [list item].id w/ the
issue is probably a bug, can you give a full example of your schema & the
data and I can look at a test?

**Comment by lwm** [comment]
The `schema` is:

```
{'type': 'array', 'items': {'type': 'string', 'minLength': 16, 'maxLength': 16}}
```

The `data` is:
```
[u'aaaaaaaaaaaaaaa', [], u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa']
```
