### ISSUE TITLE
Please move tests out of package directory

### ISSUE THREAD

**Issue by htgoebel** [jamesturk/validictory#96]
I tied packaging validoctory for guix, but running the test failed. The reasons according to [pytest good practice](https://pytest.org/latest/goodpractices.html#choosing-a-test-layout-import-rules) are:
- tests are places within the package directory
- there is an `__init__.py` in the tests directory.

**Comment by jamesturk** [comment]
What error did you get while running the tests?  They run just fine for
most use cases.

And that page actually says py.test supports both variants.

**Comment by htgoebel** [comment]
Sorry for not answering earlier, the notification must have slipped through.

I have to admit that I can not reproduce the test failures :-\

But there is another reason for moving the tests out of the package directory and removing the `__init__.py` file: Using the current structure and `find_packages()`, the test-cases will be taken as (sub-) package and be installed together with the package itself. IMO installing the tests on a production system is useless. (Tests ought to be run at install-time, and there is not need to have them available later.) And they add ca. 160 KB files, whereas the package itself has only ca. 70 KB.
